version: "1"
services:
    saver:    
        build: saver/
        # image: web_epam
        ports:
            - "8080:8080"
        networks:
            - webnet       
    web:
        build: .
        # image: web_epam
        ports:
            - "5432:5432"
        networks:
            - webnet    
networks:
    webnet:
